// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/oracle-live-session/CommandCenter.tsx": () => import("../components/mockups/oracle-live-session/CommandCenter.tsx"),
  "./components/mockups/oracle-live-session/Current.tsx": () => import("../components/mockups/oracle-live-session/Current.tsx")
};
