import { createClient } from 'npm:@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': 'https://thesurrogate.me',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization, x-client-info, apikey, x-oracle-request-id, x-oracle-session-id',
};

function json(status: number, payload: unknown): Response {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

function isSessionUuid(value: unknown): value is string {
  return typeof value === 'string'
    && /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
}

/**
 * Transcript restore is deliberately session-scoped. The session UUID is
 * generated by the client and acts as a capability; no seeker key is accepted
 * and no raw table read is exposed through PostgREST.
 */
Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') return new Response(null, { status: 200, headers: corsHeaders });
  if (req.method !== 'POST') return json(405, { success: false, error: 'Method not allowed' });
  if (!req.headers.get('Authorization')?.startsWith('Bearer ')) {
    return json(401, { success: false, error: 'Unauthorized' });
  }

  try {
    const body = await req.json().catch(() => null) as { sessionId?: unknown } | null;
    if (!isSessionUuid(body?.sessionId)) {
      return json(400, { success: false, error: 'Invalid session' });
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
    );
    const { data, error } = await supabase
      .from('conversation_turns')
      .select('role, content, turn_index')
      .eq('session_id', body.sessionId)
      .order('turn_index', { ascending: true })
      .limit(30);

    if (error) {
      console.error('conversation-history lookup failed:', error);
      return json(500, { success: false, error: 'Unable to restore conversation' });
    }

    return json(200, {
      success: true,
      turns: (data ?? []).map((turn) => ({
        role: turn.role === 'user' ? 'user' : 'oracle',
        content: typeof turn.content === 'string' ? turn.content.slice(0, 4000) : '',
        turn_index: typeof turn.turn_index === 'number' ? turn.turn_index : 0,
      })),
    });
  } catch (error) {
    console.error('conversation-history error:', error);
    return json(500, { success: false, error: 'Unable to restore conversation' });
  }
});