/**
 * oracle-world-briefing — Supabase Edge Function
 *
 * Returns a compact real-time world briefing (current events, cultural
 * trends, tech edge, street pulse) generated by Gemini 3.7 Flash with
 * Google Search grounding. Cached in oracle_world_briefing for 6 hours
 * so the majority of session prewarms hit the DB, not the Gemini API.
 *
 * GET / POST → { briefing_text: string, refreshed_at: string, cached: bool }
 *
 * Called by the client at prewarm time with a 1800ms timeout — if the
 * function is cold-starting the session proceeds without the briefing.
 *
 * Cost-abuse guards (the generation path calls a paid Gemini API):
 *  - Gateway JWT verification is ON (deployed with verify_jwt: true) — the
 *    client sends the anon key. This blocks drive-by unauthenticated calls
 *    but is NOT the cost control (the anon key is public by design).
 *  - The real cost cap is a server-side single-flight lease
 *    (acquire_briefing_lease(), SECURITY DEFINER, service-role-only): at most
 *    ONE generation ATTEMPT can start per 90s window globally, no matter how
 *    many concurrent requests arrive. One attempt makes at most TWO upstream
 *    Gemini requests: the grounded call, plus an ungrounded retry on the same
 *    model only if grounding is rejected with 400/404. All contenders — and
 *    all callers when generation fails — are served the existing briefing
 *    even if stale (marked stale: true). A stale briefing beats no briefing.
 *  - The lease is intentionally NOT released on failure: a quota-exhausted
 *    (429) upstream is retried at most once per lease window.
 */

import { createClient } from 'npm:@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization, x-client-info, apikey',
};

const CACHE_TTL_HOURS = 6;
// gemini-3.7-flash — project standard for all non-multimodal text generation.
// Grounded call uses the googleSearch tool; falls back to an ungrounded call
// on the same model if the tool is rejected (400/404).
const GEMINI_MODEL = 'gemini-3.7-flash';
const GEMINI_GROUNDED_URL =
  `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;
const GEMINI_FALLBACK_URL = GEMINI_GROUNDED_URL;

const WORLD_BRIEFING_PROMPT = `You are a real-time intelligence feed for an Oracle that witnesses the present moment.

Generate a compact world briefing covering right now. Use Google Search to ground your output in actual current events — do not fabricate or speculate.

Structure (no headers, flowing prose, intelligence-briefing tone):

1. GLOBAL PULSE (3-4 sentences): The dominant geopolitical and major news events dominating headlines this week. Be specific — real names, real events, real stakes.

2. CULTURAL FREQUENCY (3-4 sentences): What is dominating cultural discourse right now — film, music, sports, internet moments, fashion movements, viral events. Name the actual things.

3. TECH & SCIENCE EDGE (1-2 sentences): Notable developments in AI, science, or technology from the past week. Specific, not generic.

4. STREET & YOUTH SIGNAL (1-2 sentences): What is moving through youth culture, street culture, or underground scenes right now. Trends, sounds, aesthetics.

Total: 280-360 words. Terse. Intelligence briefing register. No hedging, no "as of my knowledge cutoff", no disclaimers. This is live signal.`;

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  const googleApiKey = Deno.env.get('GOOGLE_GENERATIVE_AI_API_KEY') ??
                       Deno.env.get('GOOGLE_AI_API_KEY') ?? '';
  if (!googleApiKey) {
    return new Response(
      JSON.stringify({ success: false, error: 'GOOGLE_GENERATIVE_AI_API_KEY not configured' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL') ?? '',
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
  );

  // ── Check cache ────────────────────────────────────────────────────────────
  // Kept for stale-serve: contenders and failed generations return this.
  let staleBriefing: { briefing_text: string; refreshed_at: string } | null = null;

  const jsonResponse = (body: Record<string, unknown>, status = 200) =>
    new Response(JSON.stringify(body), {
      status,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  const serveStale = (reason: string) => {
    if (staleBriefing) {
      console.log(`ℹ️ oracle-world-briefing: serving stale briefing (${reason})`);
      return jsonResponse({
        success: true,
        briefing_text: staleBriefing.briefing_text,
        refreshed_at: staleBriefing.refreshed_at,
        cached: true,
        stale: true,
      });
    }
    console.warn(`⚠️ oracle-world-briefing: no briefing available (${reason})`);
    return jsonResponse({ success: false, error: `Briefing unavailable: ${reason}` }, 503);
  };

  try {
    const { data: cached } = await supabase
      .from('oracle_world_briefing')
      .select('briefing_text, refreshed_at')
      .eq('id', 1)
      .single();

    if (cached?.briefing_text && cached?.refreshed_at) {
      staleBriefing = cached;
      const ageMs = Date.now() - new Date(cached.refreshed_at).getTime();
      const ageLimitMs = CACHE_TTL_HOURS * 60 * 60 * 1000;
      if (ageMs < ageLimitMs) {
        console.log(`✅ oracle-world-briefing: cache hit (age ${Math.round(ageMs / 60000)}m)`);
        return jsonResponse({
          success: true,
          briefing_text: cached.briefing_text,
          refreshed_at: cached.refreshed_at,
          cached: true,
        });
      }
    }
  } catch (cacheErr) {
    console.warn('⚠️ cache read failed (will refresh):', cacheErr);
  }

  // ── Single-flight lease — the actual cost cap on the paid Gemini call ──────
  // Atomic acquire (SECURITY DEFINER fn, service-role-only): at most one caller
  // per 90s window may generate. Everyone else gets the stale briefing.
  // The lease is NOT released on failure — a 429-exhausted upstream is retried
  // at most once per window instead of being hammered by every cache miss.
  try {
    const { data: gotLease, error: leaseErr } = await supabase.rpc('acquire_briefing_lease', {
      p_lease_seconds: 90,
    });
    if (leaseErr) {
      console.error('❌ lease RPC failed:', leaseErr.message);
      return serveStale('lease mechanism unavailable');
    }
    if (!gotLease) {
      return serveStale('another generation in flight or recently attempted');
    }
  } catch (leaseEx) {
    console.error('❌ lease acquisition threw:', leaseEx);
    return serveStale('lease mechanism unavailable');
  }

  // ── Lease held — fetch fresh briefing from Gemini with Search grounding ────
  console.log('🌐 oracle-world-briefing: lease acquired, fetching fresh briefing from Gemini...');

  // ── Try grounded call, fall back to ungrounded if model/tool not available ──
  const makeBody = (grounded: boolean) => JSON.stringify({
    contents: [{ role: 'user', parts: [{ text: WORLD_BRIEFING_PROMPT }] }],
    ...(grounded ? { tools: [{ googleSearch: {} }] } : {}),
    // gemini-3.7-flash is a thinking model — thought tokens count against
    // maxOutputTokens. 600 starved the visible briefing to a truncated fragment;
    // 2048 leaves room for thinking plus the full 280-360 word briefing.
    generationConfig: { temperature: 0.4, maxOutputTokens: 2048 },
  });

  let geminiRes: Response;
  let usedGrounding = true;
  try {
    geminiRes = await fetch(`${GEMINI_GROUNDED_URL}?key=${googleApiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: makeBody(true),
    });
    // Fall back to ungrounded gemini-2.5-flash if grounded model is unavailable
    if (!geminiRes.ok && (geminiRes.status === 404 || geminiRes.status === 400)) {
      console.warn(`⚠️ Grounded call ${geminiRes.status} — retrying ungrounded on same model`);
      usedGrounding = false;
      geminiRes = await fetch(`${GEMINI_FALLBACK_URL}?key=${googleApiKey}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: makeBody(false),
      });
    }
  } catch (fetchErr) {
    console.error('❌ Gemini network error:', fetchErr);
    return serveStale('Gemini request failed');
  }

  if (!geminiRes.ok) {
    const errBody = await geminiRes.text().catch(() => '');
    console.error(`❌ Gemini ${geminiRes.status}:`, errBody.slice(0, 300));
    return serveStale(`Gemini error ${geminiRes.status}`);
  }

  console.log(`✅ oracle-world-briefing: using ${usedGrounding ? 'grounded' : 'ungrounded'} generation`);

  const geminiJson = await geminiRes.json();
  const briefingText: string =
    geminiJson.candidates?.[0]?.content?.parts?.[0]?.text?.trim() ?? '';

  if (!briefingText || briefingText.length < 100) {
    console.error('❌ Empty or too-short briefing from Gemini:', briefingText.slice(0, 100));
    return serveStale('empty briefing from Gemini');
  }

  console.log(`✅ oracle-world-briefing: fresh briefing generated (${briefingText.length} chars)`);

  // ── Upsert to cache ────────────────────────────────────────────────────────
  const refreshedAt = new Date().toISOString();
  const { error: upsertErr } = await supabase
    .from('oracle_world_briefing')
    .upsert({ id: 1, briefing_text: briefingText, refreshed_at: refreshedAt });

  if (upsertErr) {
    console.error('⚠️ upsert failed (non-fatal):', upsertErr.message);
  }

  return new Response(
    JSON.stringify({
      success: true,
      briefing_text: briefingText,
      refreshed_at: refreshedAt,
      cached: false,
    }),
    { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
  );
});
