/**
 * oracle-world-briefing — Supabase Edge Function
 *
 * Returns a compact real-time world briefing (current events, cultural
 * trends, tech edge, street pulse) generated by Gemini Flash 2.0 with
 * Google Search grounding. Cached in oracle_world_briefing for 6 hours
 * so the majority of session prewarms hit the DB, not the Gemini API.
 *
 * GET / POST → { briefing_text: string, refreshed_at: string, cached: bool }
 *
 * Called by the client at prewarm time with a 1800ms timeout — if the
 * function is cold-starting the session proceeds without the briefing.
 */

import { createClient } from 'npm:@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization, x-client-info, apikey',
};

const CACHE_TTL_HOURS = 6;
// gemini-2.0-flash-exp is the stable grounding-capable model at the REST v1beta endpoint.
// Falls back to a non-grounded call with gemini-2.5-flash if grounding fails.
const GEMINI_GROUNDED_URL =
  'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent';
const GEMINI_FALLBACK_URL =
  'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent';

const WORLD_BRIEFING_PROMPT = `You are a real-time intelligence feed for an Oracle that witnesses the present moment.

Generate a compact world briefing covering right now. Use Google Search to ground your output in actual current events — do not fabricate or speculate.

Structure (no headers, flowing prose, intelligence-briefing tone):

1. GLOBAL PULSE (3-4 sentences): The dominant geopolitical and major news events dominating headlines this week. Be specific — real names, real events, real stakes.

2. CULTURAL FREQUENCY (3-4 sentences): What is dominating cultural discourse right now — film, music, sports, internet moments, fashion movements, viral events. Name the actual things.

3. TECH & SCIENCE EDGE (1-2 sentences): Notable developments in AI, science, or technology from the past week. Specific, not generic.

4. STREET & YOUTH SIGNAL (1-2 sentences): What is moving through youth culture, street culture, or underground scenes right now. Trends, sounds, aesthetics.

Total: 280-360 words. Terse. Intelligence briefing register. No hedging, no "as of my knowledge cutoff", no disclaimers. This is live signal.`;

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  const googleApiKey = Deno.env.get('GOOGLE_GENERATIVE_AI_API_KEY') ??
                       Deno.env.get('GOOGLE_AI_API_KEY') ?? '';
  if (!googleApiKey) {
    return new Response(
      JSON.stringify({ success: false, error: 'GOOGLE_GENERATIVE_AI_API_KEY not configured' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL') ?? '',
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
  );

  // ── Check cache ────────────────────────────────────────────────────────────
  try {
    const { data: cached } = await supabase
      .from('oracle_world_briefing')
      .select('briefing_text, refreshed_at')
      .eq('id', 1)
      .single();

    if (cached?.briefing_text && cached?.refreshed_at) {
      const ageMs = Date.now() - new Date(cached.refreshed_at).getTime();
      const ageLimitMs = CACHE_TTL_HOURS * 60 * 60 * 1000;
      if (ageMs < ageLimitMs) {
        console.log(`✅ oracle-world-briefing: cache hit (age ${Math.round(ageMs / 60000)}m)`);
        return new Response(
          JSON.stringify({
            success: true,
            briefing_text: cached.briefing_text,
            refreshed_at: cached.refreshed_at,
            cached: true,
          }),
          { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
    }
  } catch (cacheErr) {
    console.warn('⚠️ cache read failed (will refresh):', cacheErr);
  }

  // ── Fetch fresh briefing from Gemini with Google Search grounding ──────────
  console.log('🌐 oracle-world-briefing: fetching fresh briefing from Gemini...');

  // ── Try grounded call, fall back to ungrounded if model/tool not available ──
  const makeBody = (grounded: boolean) => JSON.stringify({
    contents: [{ role: 'user', parts: [{ text: WORLD_BRIEFING_PROMPT }] }],
    ...(grounded ? { tools: [{ googleSearch: {} }] } : {}),
    generationConfig: { temperature: 0.4, maxOutputTokens: 600 },
  });

  let geminiRes: Response;
  let usedGrounding = true;
  try {
    geminiRes = await fetch(`${GEMINI_GROUNDED_URL}?key=${googleApiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: makeBody(true),
    });
    // Fall back to ungrounded gemini-2.5-flash if grounded model is unavailable
    if (!geminiRes.ok && (geminiRes.status === 404 || geminiRes.status === 400)) {
      console.warn(`⚠️ Grounded model ${geminiRes.status} — falling back to gemini-2.5-flash ungrounded`);
      usedGrounding = false;
      geminiRes = await fetch(`${GEMINI_FALLBACK_URL}?key=${googleApiKey}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: makeBody(false),
      });
    }
  } catch (fetchErr) {
    console.error('❌ Gemini network error:', fetchErr);
    return new Response(
      JSON.stringify({ success: false, error: 'Gemini request failed' }),
      { status: 502, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }

  if (!geminiRes.ok) {
    const errBody = await geminiRes.text().catch(() => '');
    console.error(`❌ Gemini ${geminiRes.status}:`, errBody.slice(0, 300));
    return new Response(
      JSON.stringify({ success: false, error: `Gemini error ${geminiRes.status}` }),
      { status: 502, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }

  console.log(`✅ oracle-world-briefing: using ${usedGrounding ? 'grounded' : 'ungrounded'} generation`);

  const geminiJson = await geminiRes.json();
  const briefingText: string =
    geminiJson.candidates?.[0]?.content?.parts?.[0]?.text?.trim() ?? '';

  if (!briefingText || briefingText.length < 100) {
    console.error('❌ Empty or too-short briefing from Gemini:', briefingText.slice(0, 100));
    return new Response(
      JSON.stringify({ success: false, error: 'Empty briefing from Gemini' }),
      { status: 502, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }

  console.log(`✅ oracle-world-briefing: fresh briefing generated (${briefingText.length} chars)`);

  // ── Upsert to cache ────────────────────────────────────────────────────────
  const refreshedAt = new Date().toISOString();
  const { error: upsertErr } = await supabase
    .from('oracle_world_briefing')
    .upsert({ id: 1, briefing_text: briefingText, refreshed_at: refreshedAt });

  if (upsertErr) {
    console.error('⚠️ upsert failed (non-fatal):', upsertErr.message);
  }

  return new Response(
    JSON.stringify({
      success: true,
      briefing_text: briefingText,
      refreshed_at: refreshedAt,
      cached: false,
    }),
    { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
  );
});
