-- Free-run eligibility is scoped to the server-side Replicate credential.
-- It is not a universal quota and must never be inferred from local workspace
-- funds. Service-role edge functions are the only intended writers.
CREATE TABLE IF NOT EXISTS public.replicate_free_allowances (
  account_boundary text NOT NULL,
  model_slug text NOT NULL,
  status text NOT NULL DEFAULT 'available'
    CHECK (status IN ('available', 'claimed', 'exhausted', 'billing-blocked', 'catalog-drift')),
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  last_request_key text,
  last_provider_request_id text,
  last_error_category text,
  exhausted_at timestamptz,
  catalog_observed_at timestamptz,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (account_boundary, model_slug)
);

CREATE TABLE IF NOT EXISTS public.replicate_free_catalogs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  catalog_version integer NOT NULL,
  source_url text NOT NULL,
  observed_at timestamptz NOT NULL,
  refreshed boolean NOT NULL DEFAULT true,
  drift jsonb NOT NULL DEFAULT '{}'::jsonb,
  models jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.replicate_free_allowances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.replicate_free_catalogs ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.claim_replicate_free_run(
  p_account_boundary text,
  p_model_slug text,
  p_request_key text
) RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  claimed boolean := false;
  changed_rows integer := 0;
BEGIN
  INSERT INTO public.replicate_free_allowances (
    account_boundary, model_slug, status, attempt_count, last_request_key, updated_at
  ) VALUES (
    p_account_boundary, p_model_slug, 'claimed', 1, p_request_key, now()
  )
  ON CONFLICT (account_boundary, model_slug) DO UPDATE
    SET status = 'claimed',
        attempt_count = replicate_free_allowances.attempt_count + 1,
        last_request_key = EXCLUDED.last_request_key,
        updated_at = now()
    WHERE replicate_free_allowances.status = 'available'
      AND replicate_free_allowances.last_request_key IS DISTINCT FROM EXCLUDED.last_request_key;
  GET DIAGNOSTICS changed_rows = ROW_COUNT;
  claimed := changed_rows > 0;
  RETURN claimed;
END;
$$;

CREATE OR REPLACE FUNCTION public.record_replicate_free_outcome(
  p_account_boundary text,
  p_model_slug text,
  p_status text,
  p_error_category text DEFAULT NULL,
  p_provider_request_id text DEFAULT NULL,
  p_provenance jsonb DEFAULT '{}'::jsonb
) RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE public.replicate_free_allowances
  SET status = CASE
        WHEN p_status IN ('available', 'exhausted', 'billing-blocked', 'catalog-drift') THEN p_status
        ELSE 'available'
      END,
      last_error_category = left(p_error_category, 80),
      last_provider_request_id = left(p_provider_request_id, 240),
      exhausted_at = CASE WHEN p_status = 'exhausted' THEN now() ELSE exhausted_at END,
      provenance = COALESCE(p_provenance, '{}'::jsonb),
      updated_at = now()
  WHERE account_boundary = p_account_boundary AND model_slug = p_model_slug;
$$;